local ls = require("luasnip")
local t = ls.text_node
local i = ls.insert_node

return function()
  return {
    t("alert-notification-v1beta1"),
    t("alert-notification-v1beta2"),
    t("alert-notification-v1beta3"),
    t("bucket-source-v1"),
    t("bucket-source-v1beta1"),
    t("bucket-source-v1beta2"),
    t("gitrepository-source-v1"),
    t("gitrepository-source-v1beta1"),
    t("gitrepository-source-v1beta2"),
    t("helmchart-source-v1"),
    t("helmchart-source-v1beta1"),
    t("helmchart-source-v1beta2"),
    t("helmrelease-helm-v2"),
    t("helmrelease-helm-v2beta1"),
    t("helmrelease-helm-v2beta2"),
    t("helmrepository-source-v1"),
    t("helmrepository-source-v1beta1"),
    t("helmrepository-source-v1beta2"),
    t("imagepolicy-image-v1alpha1"),
    t("imagepolicy-image-v1alpha2"),
    t("imagepolicy-image-v1beta1"),
    t("imagepolicy-image-v1beta2"),
    t("imagerepository-image-v1alpha1"),
    t("imagerepository-image-v1alpha2"),
    t("imagerepository-image-v1beta1"),
    t("imagerepository-image-v1beta2"),
    t("imageupdateautomation-image-v1alpha1"),
    t("imageupdateautomation-image-v1alpha2"),
    t("imageupdateautomation-image-v1beta1"),
    t("imageupdateautomation-image-v1beta2"),
    t("kustomization-kustomize-v1"),
    t("kustomization-kustomize-v1beta1"),
    t("kustomization-kustomize-v1beta2"),
    t("ocirepository-source-v1"),
    t("ocirepository-source-v1beta2"),
    t("provider-notification-v1beta1"),
    t("provider-notification-v1beta2"),
    t("provider-notification-v1beta3"),
    t("receiver-notification-v1"),
    t("receiver-notification-v1beta1"),
    t("receiver-notification-v1beta2"),
    i(nil, "resource"),
  }
end
