local ls = require("luasnip")
local t = ls.text_node
local i = ls.insert_node

return function()
  return {
    t("alert-notification-v1beta1.json"),
    t("alert-notification-v1beta2.json"),
    t("alert-notification-v1beta3.json"),
    t("bucket-source-v1.json"),
    t("bucket-source-v1beta1.json"),
    t("bucket-source-v1beta2.json"),
    t("gitrepository-source-v1.json"),
    t("gitrepository-source-v1beta1.json"),
    t("gitrepository-source-v1beta2.json"),
    t("helmchart-source-v1.json"),
    t("helmchart-source-v1beta1.json"),
    t("helmchart-source-v1beta2.json"),
    t("helmrelease-helm-v2.json"),
    t("helmrelease-helm-v2beta1.json"),
    t("helmrelease-helm-v2beta2.json"),
    t("helmrepository-source-v1.json"),
    t("helmrepository-source-v1beta1.json"),
    t("helmrepository-source-v1beta2.json"),
    t("imagepolicy-image-v1alpha1.json"),
    t("imagepolicy-image-v1alpha2.json"),
    t("imagepolicy-image-v1beta1.json"),
    t("imagepolicy-image-v1beta2.json"),
    t("imagerepository-image-v1alpha1.json"),
    t("imagerepository-image-v1alpha2.json"),
    t("imagerepository-image-v1beta1.json"),
    t("imagerepository-image-v1beta2.json"),
    t("imageupdateautomation-image-v1alpha1.json"),
    t("imageupdateautomation-image-v1alpha2.json"),
    t("imageupdateautomation-image-v1beta1.json"),
    t("imageupdateautomation-image-v1beta2.json"),
    t("kustomization-kustomize-v1.json"),
    t("kustomization-kustomize-v1beta1.json"),
    t("kustomization-kustomize-v1beta2.json"),
    t("ocirepository-source-v1.json"),
    t("ocirepository-source-v1beta2.json"),
    t("provider-notification-v1beta1.json"),
    t("provider-notification-v1beta2.json"),
    t("provider-notification-v1beta3.json"),
    t("receiver-notification-v1.json"),
    t("receiver-notification-v1beta1.json"),
    t("receiver-notification-v1beta2.json"),
    i(nil, "resource"),
  }
end
