name: Generate Kubernetes
on:
  workflow_dispatch:
  schedule:
    - cron: "30 10 */2 * *" # Follow after yannh/kubernetes-json-schema
env:
  OUTPUT: ./lua/kubernetes-schema-snippets/autogen/kubernetes
  REPO: yannh/kubernetes-json-schema
  HEAD: master
  CLONE_PATH: kubernetes-json-schema
jobs:
  generate:
    permissions:
      contents: write
    name: Generate
    runs-on: ubuntu-latest
    concurrency:
      group: generate
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 1

      - name: Fetch latest ${{ env.REPO }} hash
        run: git ls-remote 'https://github.com/${{ env.REPO }}.git refs/heads/${{ env.HEAD }}' | cut -f1 | tee latest_hash.txt

      - name: Restore hash cache
        id: cache
        uses: actions/cache@v4
        with:
          path: latest_hash.txt
          key: kubernetes-hash

      - name: Checkout ${{ env.REPO }} repo
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO }}
          path: ${{ env.CLONE_PATH }}
          ref: ${{ env.HEAD }}
          fetch-depth: 1

      - name: Make dir
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: mkdir -p ${{ env.OUTPUT }}

      - name: Generate versions
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        shell: bash
        run: |
          find './${{ env.CLONE_PATH }}/' -maxdepth 1 -mindepth 1 -type d ! -name '.*' ! -name 'schemas' -printf '%f\n' |
          	sort |
          	./.scripts/transform-fields-to-lua.sh -f 'version' >'${{ env.OUTPUT }}/versions.lua'

      - name: Generate resources
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        shell: bash
        run: |
          find './${{ env.CLONE_PATH }}/master/' -type f ! -name '_definitions.json' ! -name 'all.json' -printf '%f\n' |
          	sed 's/\.json$//' |
          	sort |
          	./.scripts/transform-fields-to-lua.sh -f 'resource' >'${{ env.OUTPUT }}/resources.lua'

      - uses: JohnnyMorganz/stylua-action@v4
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: "false"

      - name: Format auto generated files
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        shell: bash
        run: |
          stylua ${{ env.OUTPUT }}/*

      - uses: EndBug/add-and-commit@v9
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        with:
          add: ${{ env.OUTPUT }}/
          message: "feat(autogen): update kubernetes"
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          pull: --rebase --autostash
